-- MySQL Script generated by MySQL Workbench
-- 03/06/15 00:08:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema buildmyproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buildmyproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buildmyproject` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `buildmyproject` ;

-- -----------------------------------------------------
-- Table `buildmyproject`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`accounts` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(75) NULL DEFAULT NULL,
  `city` VARCHAR(150) NULL DEFAULT NULL,
  `lat` VARCHAR(255) NULL DEFAULT NULL,
  `lng` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('FREELANCE', 'CLIENT') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`clients` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`clients` (
  `account_id` INT NOT NULL,
  `activity` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_clients_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `buildmyproject`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`projects` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `targets` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `recommendation` TINYTEXT NULL DEFAULT NULL,
  `project_type_id` INT NULL DEFAULT NULL,
  `client_id` INT NOT NULL,
  `status` ENUM('EN CREATION', 'OUVERT', 'DECISION', 'EN COURS', 'TERMINE', 'ANNULE') NULL DEFAULT NULL,
  `price` INT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_clients_idx` (`client_id` ASC),
  CONSTRAINT `fk_projects_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `buildmyproject`.`clients` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_type` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(150) NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`freelances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`freelances` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`freelances` (
  `account_id` INT NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `experience` ENUM('DEBUTANT', 'CONFIRME', 'EXPERT') NOT NULL,
  `activity` VARCHAR(150) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_freelances_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `buildmyproject`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`recommendations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`recommendations` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`recommendations` (
  `client_id` INT NOT NULL,
  `freelance_id` INT NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  `grade` INT NULL DEFAULT NULL,
  `type` ENUM('positive', 'negative') NULL DEFAULT NULL,
  `message` TINYTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`, `project_id`, `freelance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_files` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `file` VARCHAR(255) NOT NULL,
  `project_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`categories_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`categories_skills` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`categories_skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updaded_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`skills` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category_skill_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skills_categories_skills1_idx` (`category_skill_id` ASC),
  CONSTRAINT `fk_skills_categories_skills1`
    FOREIGN KEY (`category_skill_id`)
    REFERENCES `buildmyproject`.`categories_skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`freelances_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`freelances_skills` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`freelances_skills` (
  `account_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`, `skill_id`),
  INDEX `fk_freelances_skills_freelances1_idx` (`account_id` ASC),
  INDEX `fk_freelances_skills_skills1_idx` (`skill_id` ASC),
  CONSTRAINT `fk_freelances_skills_freelances1`
    FOREIGN KEY (`account_id`)
    REFERENCES `buildmyproject`.`freelances` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_freelances_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `buildmyproject`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`participates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`participates` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`participates` (
  `freelance_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `status` ENUM('ACCEPT', 'DECLINE', 'PENDING', 'CHOOSEN') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`freelance_id`, `project_id`),
  INDEX `fk_participates_projects_idx` (`project_id` ASC),
  CONSTRAINT `fk_participates_freelances`
    FOREIGN KEY (`freelance_id`)
    REFERENCES `buildmyproject`.`freelances` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participates_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `buildmyproject`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_question` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_step` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_type_id` INT NOT NULL,
  `project_question_id` INT NOT NULL,
  `step` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_step_project_type_idx` (`project_type_id` ASC),
  INDEX `fk_project_step_project_question_idx` (`project_question_id` ASC),
  CONSTRAINT `fk_project_step_project_type`
    FOREIGN KEY (`project_type_id`)
    REFERENCES `buildmyproject`.`project_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_step_project_question`
    FOREIGN KEY (`project_question_id`)
    REFERENCES `buildmyproject`.`project_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_response` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `response` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `tag` VARCHAR(150) NOT NULL,
  `price` INT NOT NULL,
  `question_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_response_project_question_idx` (`question_id` ASC),
  CONSTRAINT `fk_project_response_project_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `buildmyproject`.`project_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildmyproject`.`project_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildmyproject`.`project_tag` ;

CREATE TABLE IF NOT EXISTS `buildmyproject`.`project_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(100) NOT NULL,
  `project_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_tag_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_tag_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `buildmyproject`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
